
# The username of your bot as set with the botfather
NATALIA_BOT_USERNAME: "@MyBot"

# The bot token supplied by botfather 
NATALIA_BOT_TOKEN: "132465:MYBOTTOKEN"

# The telegram Id of the bot owner
BOT_OWNER_ID: 123456

# Admin Telegram Ids
ADMINS:
  - 132456  # my-telegram-user-id

# Rooms for the bot to moderate (Name as first param!)
ROOMS:
  - name: 'MyMainRoom'
    id: '-123456'
    # Last message and uncompressed image
    prior_welcome_message_id: 0
    lastuncompressed_image_message_id: 0
    # Prefix to add when forwarding
    forward_hashtag: '#MyMainRoom'
    # Is this the room to post the top stickers stats ? Only one room out of all can have this to 1
    is_top_stickers: 1
    # Is this the room to post the top gif stats ? Only one room out of all can have this to 1
    is_top_gifs: 1
    # Is this th room to post the wordcloud in? Only one room out of all can have this to 1
    is_wordcloud: 1
    # Is this the room to post todays users in ? Only one room out of all can have this to 1
    is_todaysusers: 1
    # Is this a room to send promotets in ?
    is_promotets: 1
    # Is this a room to pin promotets in ?
    is_promotets_pin: 1
    # Is this a room to log ?
    is_log: 1
    # Is this a room to greet new users in ?
    is_welcome: 1
    # Special welcome message (if any)
    special_welcome_message: ''
    # Is this a room to countershill in ?
    is_countershill: 1
    # Numbers of days a user should be restricted for when joining
    days_restriction_on_join: 14
    # Admin room for this group (various messages to be sent there for admins)
    admin_room_id: -132456
    # Channel to forward to (links and hashtags)
    forward_channel: -132456
  - name: 'MySideRoom'
    id: '-123456'
    # Last message and uncompressed image
    prior_welcome_message_id: 0
    lastuncompressed_image_message_id: 0
    # Prefix to add when forwarding
    forward_hashtag: '#MySideRoom'
    # Is this the room to post the top stickers stats ? Only one room out of all can have this to 1
    is_top_stickers: 0
    # Is this the room to post the top gif stats ? Only one room out of all can have this to 1
    is_top_gifs: 0
    # Is this th room to post the wordcloud in? Only one room out of all can have this to 1
    is_wordcloud: 0
    # Is this the room to post todays users in ? Only one room out of all can have this to 1
    is_todaysusers: 0
    # Is this a room to send promotets in ?
    is_promotets: 0
    # Is this a room to pin promotets in ?
    is_promotets_pin: 0
    # Is this a room to log ?
    is_log: 1
    # Is this a room to greet new users in ?
    is_welcome: 1
    # Special welcome message (if any)
    special_welcome_message: 'welcome_special'
    # Is this a room to countershill in ?
    is_countershill: 1
    # Numbers of days a user should be restricted for when joining
    days_restriction_on_join: 2
    # Admin room for this group (various messages to be sent there for admins)
    admin_room_id: -132456
    # Channel to forward to (links and hashtags)
    forward_channel: -132456

# Stop words for wordcloud 
WORDCLOUD_STOPWORDS: 
  - dont
  - include
  - these
  - words
  - in 
  - the
  - wordcloud 

# Forward URLS
# URLS matching this regex will look to be forwarded to your 'feed' room
FORWARD_URLS: 'bloomberg.com|tradingview.com|coindesk.com'


# Shill Detected
# URLS of shill links to look out for to issue a warning message
SHILL_DETECTOR: 'bitmex\.com\/register\/([a-zA-Z0-9]*)|cryptofacilities\.com\/derivatives\/([a-zA-Z0-9-_]*)|bitfinex\.com\/\?refcode=([a-zA-Z0-9]*)|simplefx\.com\/\?sfx-r=([a-zA-Z0-9-_]*)|1broker\.com\/\?c=en\/action\/r&i=([a-zA-Z0-9]*)|nitrogensports\.eu\/r\/([a-zA-Z0-9]*)|binance\.com\/\?ref=([a-zA-Z0-9]*)|deribit\.com\/reg-([a-zA-Z0-9\.]*)'
# bitmex\.com\/register\/([a-zA-Z0-9]*)|
# cryptofacilities\.com\/derivatives\/([a-zA-Z0-9-_]*)|
# bitfinex\.com\/\?refcode=([a-zA-Z0-9]*)|
# simplefx\.com\/\?sfx-r=([a-zA-Z0-9-_]*)|
# 1broker\.com\/\?c=en\/action\/r&i=([a-zA-Z0-9]*)|
# nitrogensports\.eu\/r\/([a-zA-Z0-9]*)|
# binance\.com\/\?ref=([a-zA-Z0-9]*)|
# deribit\.com\/reg-([a-zA-Z0-9\.]*)


# List of matching shill links and their counter shill links to replace the offending messages with
COUNTER_SHILL:

  - title: 'Bitmex'
    match: 'bitmex\.com\/register\/([a-zA-Z0-9]*)'
    link : 'http://bitmex.whalepool.io'

  - title: 'CryptoFacilities'
    match: 'cryptofacilities\.com\/derivatives\/([a-zA-Z0-9-_]*)'
    link : 'http://cryptofacilities.whalepool.io'

  - title: 'Bitfinex'
    match: 'cryptofacilities\.com\/derivatives\/([a-zA-Z0-9-_]*)'
    link : 'http://bitfinex.whalepool.io'

  - title: 'Simplefx'
    match: 'simplefx\.com\/\?sfx-r=([a-zA-Z0-9-_]*)'
    link : 'http://simplefx.whalepool.io'

  - title: '1broker'
    match: '1broker\.com\/\?c=en\/action\/r&i=([a-zA-Z0-9]*)'
    link : 'http://1broker.whalepool.io'

  - title: 'NitrogenSports'
    match: 'nitrogensports\.eu\/r\/([a-zA-Z0-9]*)'
    link : 'http://sports.whalepool.io'

  - title: 'Binance'
    match: 'binance\.com\/\?ref=([a-zA-Z0-9]*)'
    link : 'http://binance.whalepool.io'

  - title: 'Deribit'
    match: 'deribit\.com\/reg-([a-zA-Z0-9\.]*)'
    link : 'http://deribit.whalepool.io'




MESSAGES:

  # The message displayed to new users when they join your room
  welcome:
   - "Welcome %s, I'm Natalia, group secretary. Please PM (@WPrules_bot) see chat rules."
   - "Hi %s, welcome to the group"

  # A special welcome message for an individually special room 
  welcome_special: 'Welcome %s, this is a special chat group with a special welcome message'

  # Goodbye messages when users leave your chat
  goodbye:
   - "Smells better without ya %s"
   - "The average net worth of this group just shot up when %s left"
   - "goodbye %s. It was fun whilte it lasted"
   - "see ya %s, my sweet love"

  # If someone tries to use a command for the bot in a public channel
  # The bot will message the user telling them to pm them
  pmme:
  - "Naughty naughty %s, you know we can't talk dirty in public. PM me for that kind of talk & house rules."
  - "%s, some things a better left for behind closed doors. PM me for house rules."

  # The 'welcome' message when users first initiate pm with the bot
  start: >
   Hi %s, Welcome to X
   Please click one of the links to see how i can help you:
   /rules  - See Whalepool Rules
   /about - about us
   /admins - See list of admins to contact for help.
   /teamspeak - How to connect to teamspeak
   /teamspeakbadges - Badges rules & guides for teamspeak
   /telegram - Our telegram Channels
   /livestream - Listen to use live on youtube
   /exchanges - See where we recommend to trade
   /donation - Make a donation

  # The 'admin' extra control pannel welcome message
  admin_start: >
   %s, this is your admin control:
   /topstickers - posts the top 3 stickers from the last 3 days into the main room chat
   /topgif - post the top gif to whalepool + feed
   /topgifposters - post who are the top 5 gif posters 
   /todayinwords - Today in words...
   /todaysusers - Wordcloiud of whos active today
   /promotets 'message' - spam / promote teamspeak with a specified message.
   /shill - spam / promote various exchanges.
   /commandstats - get the command stats since the start of the month
   /joinstats - get the join stats since the start of the month
   /whalepooloverprice - list the user gifs, user messages and user joins per hour over price  

  # About page
  about: > 
   *About X*
   
   blah blah 

   /start - to go back to home


  # JSon list of admins for the '/admins' request page
  admins_json:
    "@username1":
      adminOf: "Room A and B"
      about  : "this is blah about username1"
    "@username2":
      adminOf: "Room B and C "
      about  : "this is blah about username2"

  # Rules
  rules: > 
   *Rules*
 
   blah rules blah 
   
   /start - to go back to home

  # Teamspeak info request 
  teamspeak: > 
   Blah teamspeak blah 
   
   /start - to go back to home


  # Telegram info request
  telegram: > 
   Blah telegram blah 
   
   /start - to go back to home

  # Livestream info request
  livestream: > 
   Blah livestream blah 
   
   /start - to go back to home

  # Exchanges info request
  exchanges: >
   Blah exchanges blah 

   /start - to go back to home

  # Shill exchanges / shill links
  shill: > 
   Blah my shill links blah

  teamspeakbadges: > 
   Blah teamspeak badges blah

  fomobot: > 
   Blah fomobot blah 

   /start - to go back to home

  uncompressedImage: 
    "%s, I deleted that pic you just posted because it is an uncompressed format, please use the ''compress'' format when posting pictures."

  countershillReplyStart:
    We do not allow users to post personal affiliate links.

    This prevents many problems that can poison a community.
    
    Whalepool pays for all staff, servers, competitions and costs through affiliaite revenue, thus we ask users to support whalepool by using the community affiliate links instead.

  countershillReplyCenter:
    "\n\n{0} recommended {1}, to signup on {1} please use the following link {2}"

  countershillAdminWarning:
    User {0} from {1} posted a shill link

  topstickersWarning:
    Posting... sometimes this can cause the telegram api to 'time out' ? so won't complete posting but trying anyway..

  topstickersStart:
    Whalepool most popular 3 stickers in the last 3 days are...

  topstickersCenter:
    with {0} posts..

  topstickersEnd:
    message has been posted to {0}

  topgifsStart:
    Whalepool's most popular gif ever with {0} posts is...

  topgifsEnd:
    Message has been posted to {0}

  topgifpostersStart:
    I'm naming and shaming the top 5 gif posters in {0}

  topgifpostersCenter:
    "\n#{0} - {1} with {2} gifs"

  topgifpostersEnd:
    message has been posted to {0}

  todayinWords:
    Posted today in pictures to {0}
    
  todaysusers:
    Posted today's users to {0}

  donate: > 
   If you would like to support Whalepool.io, please donate to:
   Please note, for a 'financial contributor' badge on Teamspeak, the minimium donation is 0.1 btc.  
   
   Bitcoin: 175oRbKiLtdY7RVC8hSX7KD69WQs8PcRJA
   
   Please be sure to let us know you donated :)